version: "2"

services:
  backend:
    container_name: backend
    build: ./server
    restart: always
    volumes:
      - "./server:/Backend"
      - /Backend/node_modules
    ports:
      - "5000:5000"

  web-server:
    container_name: web-server
    build: ./web-server
    restart: always
    volumes:
      - ./web-server/conf.d:/etc/nginx/conf.d
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - "8080:8080"
    depends_on:
      - backend
      - mysql
      - mongo
      - neo4j
      - cache-store

  mysql:
    container_name: primary
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./data/mysql:/var/lib/mysql"
    expose:
      - "3306"

  mongo:
    container_name: secondary
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    volumes:
      - "./data/mongodb:/data/db"
    expose:
      - "27017"
  
  neo4j:
    container_name: graphdb
    hostname: neo4j
    image: neo4j:4.2.1-enterprise
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${PASSWORD}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes' 
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_dbms_shell_enabled: 'true'
      NEO4J_dbms.ssl.policy.bolt.client_auth: NONE
      NEO4J_dbms.ssl.policy.https.client_auth: NONE
      dbms.ssl.policy.https.client_auth: NONE
      dbms.ssl.policy.bolt.client_auth: NONE     
    volumes:
      - "./data/neo4j/data:/data"
      - "./data/neo4j/logs:/logs"
      - "./data/neo4j/import:/var/lib/neo4j/import"
      - "./data/neo4j/plugins:/plugins"
    ports:
      - "7474"
      - "7473"
      - "7687"

  cache-store:
    container_name: cache-store
    image: redis
    restart: always
    ports: 
      - "6379"
    volumes:
      - "./data/redis/redis-data:/var/lib/redis"
      - "./data/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    environment: 
      REDIS_REPLICATION_MODE: master